### ISSUE TITLE
Add hint bar

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1907]
### Why/User Benefit/User Problem

As a user, I am unsure how to navigate the app with the buttons on the remote

### What / Requirements

Add a hint bar to let users know that they can click the menu button to get to the homescreen/search bar

### Acceptance Criteria (how do I know when I’m done?)

* Hint bar is shown with behaviour noted in Bram's design [specs](https://github.com/mozilla-mobile/firefox-tv/issues/1907#issuecomment-470365061)
* Hints are localized
* Hints are read by screen reader???

**Comment by liuche** [comment]
We need mocks and talked about working on this next sprint.

**Comment by brampitoyo** [comment]
# Specs
https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/hint-bar/i04/

# Behaviour
Our first iteration of the hint bar is designed to solve a very specific set of problems:

1. Users can’t access the home screen, because they don’t know that the <img width="17.5" src="https://images-na.ssl-images-amazon.com/images/G/01/support_images/GUID-0501725B-6FCE-496E-BA92-568E9F582DA3_en-US.png"> Menu button is available to use.
2. Users don’t know that the home screen contains functions that may be useful to them (e.g. pin site, request desktop site, etc.)

Because of this, the first iteration of the hint bar should be quite minimal.

## 1. When you first start Firefox
The hint bar doesn’t show up, because the menu button isn’t functional yet.

![home screen 2x](https://user-images.githubusercontent.com/51007/53925985-c13a7400-40e6-11e9-90d1-e3f8a5d859a5.png)

## 2. When you’re on a web page

* The hint bar shows up when the site is loaded
* As soon as the cursor moves down (press down on the remote), the hint bar disappears
* The hint bar shows up again every time the user has reached the top of the page again
* The hint bar shows up again when the user has reached the bottom of the page

At this point, the hint bar only contains one item:

> <img width="17.5" src="https://images-na.ssl-images-amazon.com/images/G/01/support_images/GUID-0501725B-6FCE-496E-BA92-568E9F582DA3_en-US.png"> Enter address, pinned sites, settings and more

![web page 2x](https://user-images.githubusercontent.com/51007/53926123-3312bd80-40e7-11e9-83d3-acb2373527ad.png)

We word it to emphasise the number of browser features available. This will help in case the user has landed in Firefox from the YouTube shortcut on the Fire TV homescreen, and doesn’t know that they’re inside a browser.

This will of course also help alleviate our current problem of not knowing that the menu button is accessible.

I didn’t give any hint about the <img width="17.5" src="https://images-na.ssl-images-amazon.com/images/G/01/support_images/GUID-BDEEB5AC-4B30-4E19-A848-BA8D6F499F28_en-US.png"> Back button, for two reasons:

1. Its function changes. It can return to the previous screen, it can undo the previous action, or it can quit the app, depending on where the user is currently positioned.
2. From user research, it seems as if our users instinctively know to press it without any prompt.

I decided to not ship it with this initial version of the hint bar.

## 3. When you open the home screen using the menu button

Unlike the hint bar that shows up when you’re on a web page, this hint bar is permanent and never disappears.

This hint bar contains one item:

> <img width="17.5" src="https://images-na.ssl-images-amazon.com/images/G/01/support_images/GUID-0501725B-6FCE-496E-BA92-568E9F582DA3_en-US.png"> Return to web page

![home screen overlay 2x](https://user-images.githubusercontent.com/51007/53929150-a3bed780-40f1-11e9-80cf-448d90fe721c.png)

This hint bar doesn’t contain:

1. <img width="17.5" src="https://images-na.ssl-images-amazon.com/images/G/01/support_images/GUID-F869890F-4A59-4EB9-A623-EF302CA52A45_en-US.png"> Select – it’s already clear what this button does.
2. <img width="17.5" src="https://images-na.ssl-images-amazon.com/images/G/01/support_images/GUID-BDEEB5AC-4B30-4E19-A848-BA8D6F499F28_en-US.png"> Back – same reason as given in point 2 above.

# Assets
In case we don’t have it already, here are the hardware remote icon SVG files, that have been set to fill: `non-zero`.

* https://cl.ly/62edd6a630e3/hardware-remote-back.svg
* https://cl.ly/b0c708f03c7b/hardware-remote-home.svg
* https://cl.ly/89ae72912b4b/hardware-remote-menu.svg
* https://cl.ly/4aff0520158c/hardware-remote-mic.svg
* https://cl.ly/dfa7508d4be9/hardware-remote-select.svg
* https://cl.ly/9aeb72286cfd/hardware-remote-rewind.svg
* https://cl.ly/ee1309640c1a/hardware-remote-play-pause.svg
* https://cl.ly/f5ed9ecafae9/hardware-remote-fast-forward.svg

**Comment by athomasmoz** [comment]
@brampitoyo How does the hint bar work when YouTube is open?

**Comment by liuche** [comment]
@eejay can you give some comments on how these kinds of hints should be handled by a screenreader? e.g. on the webpage, if it disappears after the user starts scrolling; is this read as it shows up; even if it's "permanent" on the screen is it read as it shows up, or as the user goes down there? I don't think this would be focusable.

@brampitoyo in #2, on the homescreen, does all the content get moved up to accommodate the hint bar, or is it layered underneath and some content would be hidden? Also can you provide some dimensions (so we can make sure it handles overscan)

@BrianNJones can you get us some strings for these? Right now this will be hints for showing the overlay/Firefox homescreen, but eventually this bar will also contain other hints (and there will be other strings needed in #1908 ).

**Comment by liuche** [comment]
Adding @mheubusch because she said she'll have Meridel look these over.

Starting on the eng work is unblocked, since we have rough mocks, but we still need:
* finalized strings (for the 2 strings: "Return to web page" and "Enter address, pinned sites, settings, and more" - see mocks for more context and https://github.com/mozilla-mobile/firefox-tv/issues/1907#issuecomment-471090254)
* pixel-specific mocks

**Comment by eeejay** [comment]
> @Eejay can you give some comments on how these kinds of hints should be handled by a screenreader? e.g. on the webpage, if it disappears after the user starts scrolling? If it appears temporarily, is this read as it shows up? When it's "permanent" on the screen, is it read as it shows up, or as the user navigates down? (this wouldn't be focusable)

I think the correct way to have that available to screen reader users is to announce that hint after the page load complete announcement. I don't think we currently do a page load complete, but we should. I plan to add it to Android Components soon.

Basically, after a user goes to a website, they would hear "Rotten Tomatoes loaded. (1 second pause) Press menu button to enter new address, access pinned sites and more"

Same with the when the homescreen first appears. The focused item will be announced, and 1 second later the user should hear "press menu button to return to web page".

How should all this be implemented? I am not 100% certain yet. It depends a lot on how VoiceView concatenates container names, so it may take some experimenting.

**Comment by brampitoyo** [comment]
@liuche wrote:
> Adding @mheubusch because she said she'll have Meridel look these over.

Thanks for assigning this to Content Strategy! I think that “Return to web page” sounds okay, but conveying the fact that the home screen contains “Search, settings and more” is less easy.

> […] on the homescreen, does all the content get moved up to accommodate the hint bar, or is it layered underneath and some part of the content would be hidden?

The latter. The content is layered underneath the hint bar. The bar appears on top of some part of the content.

> […] can you provide some dimensions (so we can make sure it handles overscan)

The spec page has dimensions ready to inspect, that has taken overscan into account. For example, the height of the hint bar is set to 72px.

@eeejay wrote:

> I think the correct way to have that available to screen reader users is to announce that hint after the page load complete announcement.

This sounds like the right approach to me.

**Comment by Baron-Severin** [comment]
> ### 2. When you’re on a web page
> -  The hint bar shows up when the site is loaded

To clarify this statement, which (if any) of these statements are true.  

The hint bar shows up when:
- A user on a web page clicks a link, then the site finishes loading
- A user on the overlay navigates from a tile or the URL bar, then the site finishes loading
- A user on the overlay closes the overlay using 'back' or 'menu' hardware buttons
- A user opens Firefox from their FTV home, and they see their last viewed page

**Comment by liuche** [comment]
I sent an email to check on strings - @athomasmoz since this is (new) mainscreen UI we probably want the strings to mostly be localized. Since we don't have final strings yet, I'm not sure this will be a finished product for the end of this sprint. However, merging in localized strings is a pretty fast process.

@Delphine just wanted to check, if we pushed 2 new strings into a PR at the end of the week, when would be a reasonable time to merge them back in?

**Comment by brampitoyo** [comment]
@Baron-Severin wrote:

> […] which (if any) of these statements are true.
> 
> The hint bar shows up when:
> 
> ✅ A user on a web page clicks a link, then the site finishes loading
> ✅ A user on the overlay navigates from a tile or the URL bar, then the site finishes loading
> ✅ A user on the overlay closes the overlay using 'back' or 'menu' hardware buttons
> ✅ A user opens Firefox from their FTV home, and they see their last viewed page

Yes on all counts – all behaviours are true.

* The hint bar shows up after any web page has finished loading – even if the web page was loaded from another web page
* The hint bar shows up when any web page reopens after accessing other places – whether that other place is the home overlay, or the Fire TV home, or any other place
* **Additionally**, the hint bar shows up when the user has reached the very bottom of the page (ie. the page stops scrolling), or when the user has reached the top of the page again (ie. after scrolling down, then scrolling back up)

If the hint bar always shows up, then when will it disappear?

* Onclick down remote button, to signal that the user is about to scroll down the page.
* Onclick up remote button, only when the page scroll position isn’t on the very top (ie. if the page has been scrolled down and about to be scrolled back up, the hint bar should also disappear

@athomasmoz’s question
> @brampitoyo How does the hint bar work when YouTube is open?

I assume that this is the scenario when the user opens YouTube using the Fire TV home screen shortcut?

In this scenario, the hint bar should still open because we consider YouTube as “just another website”. In fact, this hint bar is important to let users know that YouTube _is_ a website that lives inside a web browser, and that browser features can easily be accessed by using the menu button.

**Comment by Baron-Severin** [comment]
Thank you for the clarification!

> > @brampitoyo How does the hint bar work when YouTube is open?
> 
> I assume that this is the scenario when the user opens YouTube using the Fire TV home screen shortcut?
> 
> In this scenario, the hint bar should still open because we consider YouTube as “just another website”. In fact, this hint bar is important to let users know that YouTube _is_ a website that lives inside a web browser, and that browser features can easily be accessed by using the menu button.

I believe the issue that @athomasmoz was driving at is that there's no way to scroll on YouTube TV.  The site is a single page application that's always the size of the user's screen, but adjusts it's contents up and down as the user linearly navigates through it.  That means the hint won't reappear after being dismissed.

If it's alright with you @brampitoyo, I think that's fine for the first draft.  The hint bar will still return when watching a new video, because of the page load.  We can always iterate on this behavior as we go.

**Comment by brampitoyo** [comment]
@Baron-Severin wrote:
> I believe the issue that @athomasmoz was driving at is that there's no way to scroll on YouTube TV. The site is a single page application that's always the size of the user's screen, but adjusts it's contents up and down as the user linearly navigates through it. That means the hint won't reappear after being dismissed.

I didn’t know this. However, the “Hide hint bar onclick remote down button” is still a reasonable behaviour that will address the YouTube problem.

This way:
* When you initially navigate video within a channel (left/right buttons), the hint bar will still show up
* Only when you navigate to another channel (up/down button – but mostly down button to go to the next channel), then the hint bar will disappear

Thanks, Severin!

**Comment by Baron-Severin** [comment]
FYI @brampitoyo, our progress bar stays up for 1 second after the page finishes loading.  This means it overlays the hint bar for a significant time period, and it looks pretty odd.  LMK what you'd like me to do about that.

<img width="1127" alt="Screen Shot 2019-03-18 at 9 50 42 PM" src="https://user-images.githubusercontent.com/13170306/54581067-3c920480-49c8-11e9-845c-7571b94e7217.png">

**Comment by Delphine** [comment]
@liuche I'd say that for two strings a few days would be enough for translation. Since localizers don't have access to devices to test, they would also then need to cross check on localized screenshots if you'd like to insure good quality translations (that text fits, for example).
So I'd say 2 days for translation and a couple more for testing (in case they need to go back in and fix anything - you'd then need to re-import the latest version).

**Comment by liuche** [comment]
Here are the strings that @brampitoyo and @meridelW worked out:
On webpage:
Press "menu-button-image" for Firefox TV Home, search, settings, and more.

On FFTV home:
Press "back-button-image" to return.

@brampitoyo I don't think we have either of these icons, so we'll have to add them. Can you make them for us and attach them to this bug?

**Comment by Baron-Severin** [comment]
> @brampitoyo I don't think we have either of these icons, so we'll have to add them. Can you make them for us and attach them to this bug?

@liuche I think we're good on those.  There's an 'assets' section of the OP with everything we need.

> Here are the strings that @brampitoyo and @MeridelW worked out:
> On webpage:
> Press "menu-button-image" for Firefox TV Home, search, settings, and more.
> 
> On FFTV home:
> Press "back-button-image" to return.

@brampitoyo are those strings accurate?  I didn't think we were displaying the back button anywhere, instead using the menu button both on the home screen and on the browser.

@brampitoyo @MeridelW we will also need a content description (a11y/accessibility) string for each image.

**Comment by Baron-Severin** [comment]
@brampitoyo I'm still cleaning up the code, but this is now ready for UX review.

![hint-bar-gif](https://user-images.githubusercontent.com/13170306/54650003-ac0c0080-4a69-11e9-88c0-852e62030f46.gif)

**Comment by brampitoyo** [comment]
@Baron-Severin wrote:
> […] our progress bar stays up for 1 second after the page finishes loading. This means it overlays the hint bar for a significant time period, and it looks pretty odd.

I didn’t know that our progress bar sticks around for 1 second. Let’s make it disappear right when the page finishes loading, without any delay.

And to be extra sure that progress bar never interrupts, let’s make it appear underneath the hint bar

> I'm still cleaning up the code, but this is now ready for UX review.

The GIF looks great!

In terms of transition, I wonder if we should use the same transition that the progress bar uses, plus an upwards motion for fade-in and downwards motion for fade-out?

So, the whole thing appears in this order.

1. Homescreen
2. Click “Select” on a site
3. Homescreen disappears, white page appears
4. Progress bar fades in
5. Site is loaded
6. Progress bar fades out at the same time, or shortly afterwards
7. Hint bar fades in

This brings one edge case to mind.

Let’s say that a site is visible and ready to use/scroll down, but in reality, it’s still loading a couple of assets. Is this possible?

In this situation, will the progress bar and hint bar appear together?

What I think should happen is:

1. Progress bar appears underneath the hint bar
2. The hint bar shows up when the site is ready to use
3. If the user scrolls down while the progress bar is still loading, that’s fine. The hint bar fades out, revealing the progress bar underneath

Thoughts?

**Comment by brampitoyo** [comment]
@Baron-Severin wrote:
> Press "back-button-image" to return.
>
> I didn't think we were displaying the back button anywhere, instead using the menu button both on the home screen and on the browser.

When Meridel and I chatted yesterday, she mentioned her confusion about entering and exiting Home by pressing the same remote button.

Instead, she proposed that the back button should be the button used to perform “Close Home” or “Return to webpage”. The menu button itself can be used to “Open”, but cannot be used to “Close”.

I now wonder if doing this will introduce navigation problems that I can’t foresee (can it get users stuck in a loop?), or if it doesn’t follow Fire TV’s navigation pattern (can the menu button used to exit a Fire TV menu?).

**Comment by brampitoyo** [comment]
@liuche wrote:
> I don't think we have either of these icons, so we'll have to add them. Can you make them for us and attach them to this bug?

* https://cl.ly/62edd6a630e3/hardware-remote-back.svg
* https://cl.ly/b0c708f03c7b/hardware-remote-home.svg
* https://cl.ly/89ae72912b4b/hardware-remote-menu.svg

Icons for other remote buttons are available on https://github.com/mozilla-mobile/firefox-tv/issues/1907#issuecomment-470365061.

**Comment by Baron-Severin** [comment]
@brampitoyo 
> I didn’t know that our progress bar sticks around for 1 second. Let’s make it disappear right when the page finishes loading, without any delay.

👍 

> In terms of transition, I wonder if we should use the same transition that the progress bar uses, plus an upwards motion for fade-in and downwards motion for fade-out?

I think that transition sounds good.  Problem though: for how simple this story is, the code changes involved have been surprisingly invasive.  I'd like to get it into master before it bitrots too badly.  If it's alright with you, I'd like to:
- File a follow up issue to add the described transitions
- In the short term, push the progress bar ~ half an inch up the screen so that it doesn't visually interfere with the hint bar

> Let’s say that a site is visible and ready to use/scroll down, but in reality, it’s still loading a couple of assets. Is this possible?

Definitely possible.  Load complete events occur before all content has finished loading, it's a pretty fuzzy metric that is intended to mean that the site is ready to browse.  On top of that, we have other edge cases that will result in progress bars being displayed on top of hints (page loads, user navigates left/right [but not up/down], selects link; select tile from home, opening browser causes hint to show; etc).

> What I think should happen is:
>
> 1. Progress bar appears underneath the hint bar
> 2. The hint bar shows up when the site is ready to use
> 3. If the user scrolls down while the progress bar is still loading, that’s fine. The hint bar fades out, revealing the progress bar underneath

TBH, I'm hesitant to hide the progress bar, especially when it seems like a frequent edge case.  I'd rather move it to deconflict, either bumping it up a bit or just shifting it to the top of the screen.

> Instead, she proposed that the back button should be the button used to perform “Close Home” or “Return to webpage”. The menu button itself can be used to “Open”, but cannot be used to “Close”.

Hm, we once took out "hit hardware back while on home screen to exit app" functionality and got a _lot_ of complaints.  Seems like that's a pretty important flow to people, I'm pretty concerned about breaking it.

**Comment by Baron-Severin** [comment]
@brampitoyo could I get your input on a few questions in https://github.com/mozilla-mobile/firefox-tv/issues/1907#issuecomment-474671922?

**Comment by eeejay** [comment]
Checking back on accessibility/VoiceView support. I think it may be worth looking into making the hint view a [live region](https://developer.android.com/reference/android/view/View.html#attr_android:accessibilityLiveRegion). It might be an easy win.

**Comment by Baron-Severin** [comment]
@MeridelW in app, this string feels a little confusing to me.  Would you be ok with using "Press [back] to return to website"? 

<img width="1117" alt="Screen Shot 2019-04-02 at 11 29 01 AM" src="https://user-images.githubusercontent.com/13170306/55427339-9b648b80-553b-11e9-8ea0-3738c1b93342.png">

**Comment by Baron-Severin** [comment]
@eeejay I'm having trouble working out a good accessibility experience for this.  The hint view pops in and out pretty frequently, so the announcements are fairly regularly either interrupting or being interrupted by important page content.  Do you have any advice on how to approach this?

**Comment by brampitoyo** [comment]
@Baron-Severin Hi Severin, it’s nice to be back in this project again.

Let me respond to your questions inline:

> In the short term, push the progress bar ~ half an inch up the screen so that it doesn't visually interfere with the hint bar
> […]
>  Load complete events occur before all content has finished loading, it's a pretty fuzzy metric that is intended to mean that the site is ready to browse. On top of that, we have other edge cases that will result in progress bars being displayed on top of hints.
> […]
> I'm hesitant to hide the progress bar, especially when it seems like a frequent edge case. I'd rather move it to deconflict, either bumping it up a bit or just shifting it to the top of the screen.

I agree with all your assessments. When we make the progress and hint bar transition into/between each other, they have heaps of chances to overlap and conflict.

Plus, both bars operate independently. A webpage can be ready to browse (which will show the hint bar) even when the progress bar isn’t yet complete.

So let’s just move the progress bar up. I’m not sure if you’ve done this already. Let’s moving it up by multiples of 8px: 16, 24, 32, 40, 48, etc. See which one looks the best.

**Comment by Baron-Severin** [comment]
@brampitoyo happy to have you back!

Pushing up 64dp and moving to the bottom right both seem to work decently.  Bottom right can cover some of the hint when the URL is long, but pushing up looks a little off when the hint bar is disabled.  Let me know what you would prefer

[progress-bar-option-screenshots.zip](https://github.com/mozilla-mobile/firefox-tv/files/3055831/progress-bar-options.zip)

Also, would you mind playing around with this APK and giving a general thumbs up/down on the UX?

[hint-bar.apk.zip](https://github.com/mozilla-mobile/firefox-tv/files/3055725/hint-bar.apk.zip)

**Comment by eeejay** [comment]
> @eeejay I'm having trouble working out a good accessibility experience for this. The hint view pops in and out pretty frequently, so the announcements are fairly regularly either interrupting or being interrupted by important page content. Do you have any advice on how to approach this?

Yeah, just tried your build, and it looks like that won't work well. Here is the official, Amazon sanctioned way of providing usage hints to VoiceView users:
https://developer.amazon.com/docs/fire-tv/implement-voiceview-accessibility-features-fire-os.html#implementing-usage-hints-voiceview

I tinkered around with it a bit, and it seems to work as expected.

**Comment by brampitoyo** [comment]
@Baron-Severin I would prefer pushing the progress bar up 64dp but staying on the same side – completely out of the way of the hint bar, so there’s no chance of conflict.

@eeejay Thanks for checking our accessibility along the way. I would like to set up a separate time to work with you, so our design is inclusive and universal-first – I just need to get up to speed on how things work on FFTV and FFES.

**Comment by Baron-Severin** [comment]
Thanks @eeejay, those look really helpful.  I'm not sure how we should implement them here though.  The goal of the hint bar is to very frequently display unobtrusive hints to the user.  Whatever tools we use, if we send a VoiceView event every time we show a hint bar, it will be often enough so as to make the app unusable.  I'm not sure what our strategy here should be.

**Comment by eeejay** [comment]
This isn't an event, rather a property the accessible object stores, and VoiceView figures out an opportune time to tell the user about it. So in this case, once the user enters a region with accessibility focus, there will be a pause after the primary navigation speech, and then the user will hear the hint. I think it will be very subtle. This works well when the hint is region-related. As for random hints that are pushed to the user at any given time regardless of their interaction, we may need to do announcements or live regions.

**Comment by Baron-Severin** [comment]
Right, but I'm not sure what region to tie to it.  The new hint bar is basically always up when the overlay is open, and it tells users how to close it.  It's conceptually tied to the overlay as a whole, not any particular part.

The browser hint bar is even worse.  It appears any time the user navigates to a new page (which is when the page title is being announced), and since we use a cursor for navigation, our browser doesn't actually focus anything at all.  There aren't any regions we even _could_ associate it with.

I think these would have to be announcements, but I'm not sure when they should be triggered.

**Comment by brampitoyo** [comment]
@Baron-Severin @eeejay Although the hint bar visually shows up all the time, I think that it should only be announced audibly only **once per session**. Maybe when the first site has finished loading?

**Comment by brampitoyo** [comment]
@Baron-Severin I just had the chance to review your design.

The hint bar looks good (in other words, no design alteration is necessary), but there are a few bugs:

1. When my cursor reaches the very top of the screen (ie. I manually press up on the remote) and I release the up button, the hint bar doesn’t automatically show up, unless:
    * I keep pressing up for ~0.25 seconds longer
    * I press up again

Expected behaviour: as soon as my cursor reaches the top of the screen, the hint bar should show up.

2. On YouTube TV, the hint bar shows up every time I press up on the remote, even though I’m not on the very top of the page:
    * Is this a bug with all TV-optimised websites?
    * Is there a way for us to detect “the very top of the page” if we don’t have a cursor?

Expected behaviour: the hint bar should re-show again only when I reached the link on the top of the page (this link is “Recommended”, and sits on the same level as “Latest”, “Entertainment”, “Music”, etc.)

I think @athomasmoz has acknowledged the second issue, as well?

That’s all my reports. Otherwise, it’s ready to ship!

**Comment by athomasmoz** [comment]
I tried these out. I'll log a bug for #1, but I don't think it's a release blocker. For #2, I was unable to reproduce it. In fact, when I'm in YouTube and scroll to the top or bottom, I can't get the hint bar to show up at all. I'm using master with the hint bar experiment set to true. @Baron-Severin what behaviour do you see? I'm wondering if it's different because I'm on a different version than Bram.

**Comment by Baron-Severin** [comment]
@athomasmoz Hm, I'm on the current master and I'm seeing the same behavior as Bram described.  What version and device are you on?  I can do some investigating.

@brampitoyo @athomasmoz 
1 - I think this should be an easy fix.  I'll timebox it, and we can open a follow-up if I'm wrong
2 - I don't think we can do much about this.  I think we should disable hints when on a YouTube video, and keep the current behavior on the YT home.  It won't impact other sites (we use a cursor everywhere else).

**Comment by Baron-Severin** [comment]
> @athomasmoz Hm, I'm on the current master and I'm seeing the same behavior as Bram described. What version and device are you on? I can do some investigating. Nevermind, YouTube behavior seems different every time I test it. I'll try to figure it out.
> 
> @brampitoyo @athomasmoz
> 1 - I think this should be an easy fix. I'll timebox it, and we can open a follow-up if I'm wrong The easy fix has an unacceptable impact on performance. Let's put this in a follow up.
> 2 - I don't think we can do much about this. I think we should disable hints when on a YouTube video, and keep the current behavior on the YT home. It won't impact other sites (we use a cursor everywhere else).

- Weird, inconsistent YouTube behavior -> fixed in #2035. Behavior is now consistent on YouTube home, and the bar is disabled on videos
- Delayed show hint when cursor on top of screen - fixed in #1912 (there's still a slight delay due from how the OS sends key events, but it's a lot better)
