### ISSUE TITLE
[2386] Mitigate shifted videos

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#2526]
Related to #2386

### Acceptance Criteria

* Shift in videos on GolfDigest is fixed
* Golf Digest and other sites in the MVP categories list are retested
* Any sites where video playback is fixed are added to the homescreen

### Steps to reproduce
Visit https://video.golfdigest.com/watch/golf-digest-stephen-curry

### Expected behavior
Video is centred in container while minimized and fullscreen.
### Actual behavior
Video is only on right half minimized and in top right corner in fullscreen.

Investigating the css for video player on https://video.golfdigest.com/watch/golf-digest-stephen-curry:
<img width="209" alt="image-20190710173213342" src="https://user-images.githubusercontent.com/11432165/61006971-ae0c0f00-a339-11e9-95da-0fd7d6e78c98.png">

It seems that the `transform` property is not being respected because checking and unchecking that value does not change anything. But changing the `left` value moves the video. 
Unchecking both the `transform` and `left` properties puts the video in the correct place. Severin mentioned `transform/left` is a common tactic to center content in CSS.

This was discovered because the video was offset in the WebView by an amount similar to the `<video>` CSS property `offsetLeft`: maybe we can use these properties to determine when we should or should not be trying to fix this issue on a given web page.

### Potential options for fixes
* Inject JS to handle CSS and remove both `transform` and `left`
* Other options?

This should be timeboxed to _____.

### Device information
* Fire TV device: ?
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?
* Turbo Mode: ?

**Comment by Baron-Severin** [comment]
As a hacky testing solution, I injected a script that would find all `<video>` elements and clear their `transform` and `left` properties once per second.  I picked out five sites that previously showed videos out of position (Sbnation, CNBC, NY Post, BBC, and TIME), and two that previously worked (CNN, Fox News).

Video problems on CNBC were fixed.

Video positions on all other sites (both those that worked and failed) seemed to be unaffected.

**Comment by Baron-Severin** [comment]
I tested all sports sites that either 1) previously worked, or 2) failed due to weird video placement.  These were my results

Previously broken (offset videos)
CBS sports - fixed
NHL - not fixed
Deadspin - couldn't even get any videos to start
Ncaa - full screened, still cut off. Spent time trying to fix, no luck
Sbnation - fixed
WWE - not fixed. Full screened video is still offcenter
Masters - not fixed. Also perf is horrible, site slows down then crashes, consistently
Runners world - adding `top:0px` to `<video>`s fixes normal play, but fullscreen is still a full black screen
Mens health - sometimes fullscreen works, sometimes it doesn't. Haven't managed to correct it
Thrasher magazine - Video controls are cut off at the bottom in regular mode. Fullscreen sometimes works, sometimes is cut off and all black
womens health mag - full screened video is often offset. Unable to fix
Shape - still broken
Golf digest - still broken

SPORTS: PREVIOUSLY WORKED
NBC sports - still works
Formula1 - still works


Totals:
All previously working sites were unaffected by the fix
Of 13 previously broken sites, this seems to fix 2 of them.  I was unable to find any additional CSS tweaks to improve any others.

**Comment by athomasmoz** [comment]
Thanks for the due diligence on this @Baron-Severin ! Even though it only fixed 2 sites in the sports section, that's a win for us to be able to add them to the homescreen. I'm guessing it's also fixed other sites on the web too. I can help retest some of the other MVP sites once your fix goes out

**Comment by abodea** [comment]
We did some additional testing on the following websites using **4k Stick and 2nd Gen Stick** on the latest **Firefox TV v4.1 LAT2 version.** and there are still issues.
Please note that I marked with ❌ and ✔️ the websites but some of them with ✔️ are working but still have some issues that we are aware of, having that check mark doesn't mean that they are fully working.

| Previously broken | Status | Works? |
| ------------- | ------------- | ------------- |
| **CBS sports**  | Actually no videos can be played on Fenix, Chrome (Android &Desktop). Odd display of the home page of the website (issue #2596)  | ❌ |
|     **NHL**   | Video can't be played | ❌ |
| **Deadspin** | Works ok in both normal view as well as in full screen mode, the only issue is that the video playback is lagging | ✔️ |
| **Ncaa** | Video can't be played | ❌ |
| **Sbnation**  | Not working, shifted image in both normal view as well as in full screen view #2599  | ❌ |
| **WWE**  | Works ok in normal view shifted for full screen | ✔️ |
|**Masters** |Works ok in normal view, shifted for full screen  | ✔️|
| **Runners world** | Works ok in normal view, shifted for full screen (Black screen)  | ✔️ |
| **Mens health** | Some videos properly worked in normal view, some didn't. None of the videos worked in full screen view   | ❌ |
| **Thrasher magazine**  | Works ok in normal view, but the video controls aren't displayed. Shifted image in full screen mode | ✔️ |
| **Womens health** |Not working, shifted immage in both normal view as well as in full screen view | ❌ |
| **Shape** | At first attempt the video didn't play in normal view. I've tapped on the full screen view and after exiting the video played o in normal view. Afterwards, all the other videos played ok in normal view, but none played ok in full screen view   | ❌ |
| **Golf digest** | Works ok in normal view, but the fullscreen icon flickers showing the volume button #2597. Shifted image in full screen  | ✔️ |
|**NBC sports** | Only one video had shifted image in full screen, the rest of them worked properly in both normal and full screen view | ✔️ |
| **F1** | Works ok in both normal view as well as in full screen mode | ✔️ |

**Comment by Baron-Severin** [comment]
Closed by https://github.com/mozilla-mobile/firefox-tv/pull/2557

**Comment by AndiAJ** [comment]
Hi @athomasmoz & @Baron-Severin , considering the fact that this was partially fixed, how should we tackle the rest of the problematic websites e.g. dailymotion or vimeo ?

**Comment by Baron-Severin** [comment]
Sorry for the late response @AndiAJ, I was on PTO.  I'm not sure I understand the question.  I know we're looking for additional workarounds, and testing to see if any sites have been suitably fixed, but I don't think we have any other actions to take at this time.  Does that answer your question?

**Comment by AndiAJ** [comment]
Hi, @Baron-Severin I just wanted to know if we should open new issues in case we encounter similar problems ? 
e.g. one issue for dailymotion, another one for vimeo.

Or should we treat this as a general problem ?

**Comment by Baron-Severin** [comment]
I think it would make sense to open one issue, and list all the sites where it's being encountered in that issue.  I'll defer to @athomasmoz here though.

**Comment by athomasmoz** [comment]
Agreed. I think that's the best approach because we have all sites where it's been encountered in one place and can test them
